name: CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Cambia esto a la versión de Node.js que estés utilizando

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
